### ISSUE TITLE
Configure The Server

### ISSUE THREAD

**Issue by AsyncChaka** [CriLisCraft/Issue-Tracker#82]
###### 
# Current Stage
###### 
- [x] Download Plugins
- [x] Configure Plugins
- [x] Verify Loading of Plugins
- [x] Add server icon
- [x] Configure Permissions
- [x] Update Gamerules
- [x] Build Spawn
- [x] Build Market
- [x] Beta Test
- [x] Add Features
- [x] Test Again
- [x] Update Mod Training
- [x] Verify Public Date
- [x] Complete
###### 
# Reference
###### 
- [x] Announcer
- [x] AsyncWorldEdit
- [x] BetterAlias
- [x] ChestShop
- [x] CommandBook
- [x] CommandSpy
- [x] ConsoleSay
- [x] CostRepair
- [x] CraftBook
- [x] CraftConomy3
- [x] cTablist
- [x] EchoPet
- [x] Enjin
- [x] ExtraStorage
- [x] FirstJoinPlus
- [x] GriefNotice
- [x] HeroChat
- [x] HomeSpawnPlus
- [x] KeepItems
- [x] LegendaryWeapons
- [x] LWC
- [x] MCBans
- [x] mcMMO
- [x] mcMMO-PA
- [x] MobHunting
- [x] Multiverse
- [x] OpenInv
- [x] PermissionsEx
- [x] PlayerData
- [x] Prism
- [x] RandomTP
- [x] BukkitRFL
- [x] ServerSigns
- [x] SimpleVoteListener
- [x] Spawner
- [x] TelePlusPlus
- [x] TimTheEnchanter
- [x] TreeAssist
- [x] VanishNoPacket
- [x] Vault
- [x] VirtualPack
- [x] Votifier
- [x] WelcomeNewPlayers
- [x] WorldBorder
- [x] WorldEdit
- [x] WorldGuard

**Comment by Chaka15205** [comment]
VirtualPack and ConsoleSay

**Comment by AsyncChaka** [comment]
RandomTP is broken We need a new random tp plugin
